### ISSUE TITLE
packwiz support

### ISSUE THREAD

**Issue by TheAlan404** [ParadigmMC/mcman#12]
Support for packwiz using most likely rpackwiz

## TODO

- [x] structs
- [x] import from a packwiz pack
- [x] clientside mods in server.toml
- [ ] packwiz export (clientside)
