### ISSUE TITLE
v0.4 Release Roadmap

### ISSUE THREAD

**Issue by TheAlan404** [ParadigmMC/mcman#31]
# v0.4: The Rewrite

The 0.4 release will include tons of new features and improvements overall.

Current progress can be found under the [source-rewrite](https://github.com/ParadigmMC/mcman/tree/source-rewrite) branch

## Summary

Here are some notable things:

- ⚡ `0.4` adds a new `server/.mcman.lock` file (called the **lockfile**) containing metadata about the last build. This file will be used (if it exists) to validate and skip files that do not need to be downloaded or bootstrapped again (making builds get a lot faster)
- 📦 `0.4` also adds global **caching** - most downloaded files and useful metadata will be cached under these directories.
  - Windows: `%localappdata%/mcman`
  - Linux: `~/.cache/mcman` (most likely)
- :octocat: **Github rate limiting** should be fixed! I mean unless you have like a billion `ghrel`'s. Because of the caching system, metadata from GitHub get cached. `mcman` can use this metadata to send *conditional requests* which do not count towards the rate limit.
- 🔒 File **hash checksums** are also implemented, meaning more secure and stable downloads. (Yes, cached files also get checked)
- 📜 **Visual overhaul**: `mcman`'s got a new look. There are now progress bars and spinners everywhere, and its more consistent overall.
- ☔ **Hot reloading** with development sessions, you can develop your server without having to build it every time you change something!
- 🌐 **Worlds** You can now download (in `server.toml`) and store (`worlds/`) worlds!
- ☕ **Java environment variables** You can now set the java version to use (`server.toml`) and mcman will use `JAVA_*_BIN` variables to find and use the java with the version
- ✨ **Networks** Have multiple servers? `network.toml` is now here! Have common addons, common configs and variables! It can also help you manage port configurations with special variables like `${NETWORK_VELOCITY_SERVERS}`
- 📎 **mclo.gs** `mcman run` and `mcman dev` can auto-upload logs to mclo.gs

## Progress

- [x] Internal common file resolving
- [x] File Checksums
  - [x] Download
  - [x] Copy from Cache
- [ ] Retry mechanism
- [x] #19
  - [x] Lockfile-based building
    - [x] Skip more downloadables easily
    - [x] 
    - [x] Bootstrap only changed files
- [ ] #13 
- [x] Local (global) caching
  - [x] Downloaded files
  - [x] Metadata
    - [x] GitHub
  - [x] `mcman cache` command
    - [x] `mcman cache open`
    - [x] `mcman cache list`
    - [x] `mcman cache clear`
- [x] #27 
- [x] #3
  - [x] using env `GITHUB_TOKEN`
  - [x] cache api will also help
- [x] refactor basically everything
- [x] Maven Downloadable
- [x] Refactor Jenkins API
- [x] Forge, NeoForge, etc.
- [x] Hangar Downloadable
- [x] #7 
- [x] #26 
  - [x] Build step
    - [x] Download
    - [ ] Unpack
  - [x] `mcman world unpack`
  - [x] `mcman world pack`
  - [x] impl `.gitattributes`
- [ ] Some global flags if possible
  - [ ] `--no-cache`
  - [ ] `-v <prop>=<value>` or `--var <prop>=<value>`
  - [ ] `--skip-md` and `--render-md`
  - [ ] `--dry` (do not save files)
- [ ] `mcman print <var>` could be useful for scripts
- [ ] maybe, just maybe, json output

:3
