### ISSUE TITLE
v2 Roadmap

### ISSUE THREAD

**Issue by TheAlan404** [ParadigmMC/mcman#66]
# Brainstorming
- [ ] how can we have commands that add/remove/change addons?

# Core
- [x] mrpack source
- [x] packwiz source
- [x] file source
- [ ] folder source
- [x] `Step::Download`
- [x] `Step::CacheCheck`
- [ ] `Step::ExecuteJava`

# Build
- [x] Addons
- [x] Server Jar
- [ ] Worlds
- [ ] Datapacks
- [ ] Scripts
- [ ] Hooks
- [ ] Bootstrapping

# Commands
- [ ] `mcman init`
- [ ] `mcman init network`
- [ ] `mcman sources add`
- [x] `mcman sources list`
- [x] `mcman build` (partially)
- [ ] `mcman update`
- [ ] `mcman cache [clear/open/path]`
- [ ] `mcman run`
- [ ] `mcman dev`
